apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-users
  labels:
    app: ms-users
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ms-users
  template:
    metadata:
      labels:
        app: ms-users
    spec:
      containers:
        - name: ms-users
          image: arturbdev/ms-users:v0.0.2
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
